import { Quote } from "../types";

export const quotes: Quote[] = [
  {
    productName: "Raw Cashew Nuts",
    price: "$250",
    status: "pending",
    updatedAt: "2025-01-12T10:20:00Z",
    description: "Seeking best quality raw cashew nuts for export.",
    buyer: { firstName: "John", lastName: "Adeyemi" },
    seller: { firstName: "Tunde", lastName: "Okafor" },
    address: "Lagos, Nigeria",
    minLead: 5,
    minLeadPeriod: "days",
    maxLead: 12,
    maxLeadPeriod: "days",
    quantity: "20 tons",
  },
  {
    productName: "Sesame Seeds",
    price: "₦450000",
    status: "replied",
    updatedAt: "2025-01-10T14:50:00Z",
    description: "Clean sesame seeds required for local processing.",
    buyer: { firstName: "Grace", lastName: "Olawale" },
    seller: { firstName: "Emeka", lastName: "Chike" },
    address: "Abuja, Nigeria",
    minLead: 1,
    minLeadPeriod: "weeks",
    maxLead: 2,
    maxLeadPeriod: "weeks",
    quantity: "500 kg",
  },
  {
    productName: "Ginger",
    price: "$180",
    status: "accepted",
    updatedAt: "2025-01-11T09:30:00Z",
    description: "Dry split ginger needed for export shipment.",
    buyer: { firstName: "Mohammed", lastName: "Bello" },
    seller: { firstName: "Adamu", lastName: "Saleh" },
    address: "Kano, Nigeria",
    minLead: 3,
    minLeadPeriod: "days",
    maxLead: 1,
    maxLeadPeriod: "weeks",
    quantity: "2 tons",
  },
  {
    productName: "Cocoa Beans",
    price: "$320",
    status: "rejected",
    updatedAt: "2025-01-08T16:10:00Z",
    description: "Premium grade cocoa beans required.",
    buyer: { firstName: "Linda", lastName: "Ebere" },
    seller: { firstName: "James", lastName: "Fadipe" },
    address: "Ondo, Nigeria",
    minLead: 2,
    minLeadPeriod: "weeks",
    maxLead: 1,
    maxLeadPeriod: "months",
    quantity: "5 tons",
  },
  {
    productName: "Maize",
    price: "₦220000",
    status: "pending",
    updatedAt: "2025-01-15T11:12:00Z",
    description: "High moisture-free white maize required.",
    buyer: { firstName: "Bola", lastName: "Shittu" },
    seller: { firstName: "Kunle", lastName: "Adejumo" },
    address: "Osogbo, Nigeria",
    minLead: 4,
    minLeadPeriod: "days",
    maxLead: 10,
    maxLeadPeriod: "days",
    quantity: "1 ton",
  },
  {
    productName: "Soybeans",
    price: "$150",
    status: "replied",
    updatedAt: "2025-01-14T08:44:00Z",
    description: "Clean soybeans needed for animal feed production.",
    buyer: { firstName: "Janet", lastName: "Ojo" },
    seller: { firstName: "Halima", lastName: "Usman" },
    address: "Kaduna, Nigeria",
    minLead: 6,
    minLeadPeriod: "days",
    maxLead: 2,
    maxLeadPeriod: "weeks",
    quantity: "3 tons",
  },
  {
    productName: "Palm Kernel Oil",
    price: "$95",
    status: "accepted",
    updatedAt: "2025-01-13T17:30:00Z",
    description: "Pure palm kernel oil for cosmetic processing.",
    buyer: { firstName: "Roland", lastName: "Igwe" },
    seller: { firstName: "Ngozi", lastName: "Chima" },
    address: "Enugu, Nigeria",
    minLead: 2,
    minLeadPeriod: "days",
    maxLead: 7,
    maxLeadPeriod: "days",
    quantity: "800 liters",
  },
  {
    productName: "Rice (Unprocessed Paddy)",
    price: "₦350000",
    status: "pending",
    updatedAt: "2025-01-12T15:55:00Z",
    description: "Paddy rice needed for mill processing.",
    buyer: { firstName: "Damola", lastName: "Adekunle" },
    seller: { firstName: "Chinedu", lastName: "Opara" },
    address: "Benue, Nigeria",
    minLead: 5,
    minLeadPeriod: "days",
    maxLead: 3,
    maxLeadPeriod: "weeks",
    quantity: "4 tons",
  },
  {
    productName: "Shea Butter",
    price: "$70",
    status: "replied",
    updatedAt: "2025-01-11T13:40:00Z",
    description: "Raw unrefined shea butter needed.",
    buyer: { firstName: "Rebecca", lastName: "Ogunleye" },
    seller: { firstName: "Musa", lastName: "Tanko" },
    address: "Niger State, Nigeria",
    minLead: 2,
    minLeadPeriod: "weeks",
    maxLead: 1,
    maxLeadPeriod: "months",
    quantity: "200 kg",
  },
  {
    productName: "Dried Hibiscus Flower",
    price: "$260",
    status: "accepted",
    updatedAt: "2025-01-13T09:12:00Z",
    description: "Premium dry hibiscus flower needed for export to Mexico.",
    buyer: { firstName: "Samuel", lastName: "Edet" },
    seller: { firstName: "Rita", lastName: "Okon" },
    address: "Cross River, Nigeria",
    minLead: 1,
    minLeadPeriod: "weeks",
    maxLead: 3,
    maxLeadPeriod: "weeks",
    quantity: "1.5 tons",
  },
];

export const quoteInfo: Quote = {
  productName: "Raw Cashew Nuts",
  price: "$250",
  status: "replied",
  updatedAt: "2025-01-12T10:20:00Z",
  description:
    "Looking to purchase high-quality export-grade raw cashew nuts. Moisture level must not exceed 10%.",

  buyer: {
    firstName: "John",
    lastName: "Adeyemi",
  },

  seller: {
    firstName: "Tunde",
    lastName: "Okafor",
  },

  address: "Ikeja, Lagos, Nigeria",

  minLead: 5,
  minLeadPeriod: "days",
  maxLead: 12,
  maxLeadPeriod: "days",
  quantity: "20 tons",
  productImage: "/assets/dummy/prodImg.jpg",
};
