export const agroInsights = [
  {
    id: 1,
    title: "How Climate Change is Affecting Crop Yields in West Africa",
  },
  { id: 2, title: "Top 10 Profitable Cash Crops in 2026" },
  { id: 3, title: "The Rise of AgriTech Startups in Africa" },
  { id: 4, title: "Smart Irrigation Systems Every Farmer Should Know" },
  { id: 5, title: "Export Opportunities for Nigerian Agricultural Products" },
  { id: 6, title: "Understanding Commodity Price Fluctuations" },
  { id: 7, title: "Organic Farming vs Conventional Farming: What Pays More?" },
  { id: 8, title: "Post-Harvest Losses: Causes and Prevention Strategies" },
  { id: 9, title: "How to Improve Soil Fertility Naturally" },
  { id: 10, title: "Agricultural Financing: Funding Options for Farmers" },

  { id: 11, title: "Digital Marketplaces Transforming Agricultural Trade" },
  { id: 12, title: "Livestock Farming Trends to Watch This Year" },
  { id: 13, title: "Best Practices for Greenhouse Farming" },
  { id: 14, title: "The Role of Blockchain in Agricultural Supply Chains" },
  { id: 15, title: "How to Scale Your Farm from Small to Commercial Level" },
  { id: 16, title: "Government Policies Impacting Agribusiness in Africa" },
  { id: 17, title: "Cassava Processing: Turning Raw Produce into Profit" },
  { id: 18, title: "Maize Production Guide for Maximum Yield" },
  { id: 19, title: "Rice Farming Innovations Boosting Productivity" },
  { id: 20, title: "Poultry Farming: Common Mistakes to Avoid" },

  { id: 21, title: "Agricultural Export Documentation Explained" },
  { id: 22, title: "The Future of Hydroponics in Urban Farming" },
  { id: 23, title: "How AI is Revolutionizing Precision Agriculture" },
  { id: 24, title: "Top Agricultural Equipment Every Farm Needs" },
  { id: 25, title: "Women Leading the Future of Agribusiness" },
  { id: 26, title: "Youth Opportunities in Modern Agriculture" },
  { id: 27, title: "How to Reduce Farm Operating Costs" },
  { id: 28, title: "Understanding Global Commodity Markets" },
  { id: 29, title: "Best Storage Practices for Grains" },
  { id: 30, title: "Exporting Sesame Seeds: What You Should Know" },

  { id: 31, title: "Climate-Smart Agriculture Techniques" },
  { id: 32, title: "How to Access Agricultural Grants and Subsidies" },
  { id: 33, title: "The Role of Cooperatives in Farm Growth" },
  { id: 34, title: "Improving Agricultural Supply Chain Efficiency" },
  { id: 35, title: "Agro-Processing: Adding Value to Farm Produce" },
  { id: 36, title: "The Impact of Exchange Rates on Agro Exports" },
  { id: 37, title: "Best Crops for Dry Season Farming" },
  { id: 38, title: "Farm Risk Management Strategies" },
  { id: 39, title: "The Importance of Farm Record Keeping" },
  { id: 40, title: "How to Attract Investors to Your Agribusiness" },

  { id: 41, title: "Cold Chain Logistics in Agriculture" },
  { id: 42, title: "Agricultural Insurance: Why It Matters" },
  { id: 43, title: "Improving Farm Productivity with Data Analytics" },
  { id: 44, title: "Sustainable Palm Oil Production Practices" },
  { id: 45, title: "Aquaculture Farming: Opportunities and Challenges" },
  { id: 46, title: "Export Standards and Quality Control in Agriculture" },
  { id: 47, title: "How to Build a Strong Agribusiness Brand" },
  { id: 48, title: "Emerging Trends in Global Food Demand" },
  { id: 49, title: "Renewable Energy Solutions for Farms" },
  { id: 50, title: "The Future of Agricultural Trade in Africa" },
];
